# Generated by Django 5.2.6 on 2025-10-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='costo',
            new_name='precio_compra',
        ),
        migrations.AddField(
            model_name='producto',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
    ]
