# Generated by Django 5.2.6 on 2025-10-13 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_costo_producto_precio_compra_producto_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='precio_venta',
        ),
    ]
