# Generated by Django 5.2.6 on 2025-11-10 21:27

from django.db import migrations, models


def migrate_precios_to_prenda(apps, schema_editor):
    """Migra los precios de Producto a Prenda"""
    Prenda = apps.get_model('inventario', 'Prenda')
    Producto = apps.get_model('inventario', 'Producto')
    
    # Para cada prenda, copiar los precios de su producto relacionado
    for prenda in Prenda.objects.all():
        producto = prenda.producto
        prenda.precio_compra = producto.precio_compra
        prenda.precio_venta = producto.precio_venta
        prenda.save()


def reverse_migrate_precios_to_producto(apps, schema_editor):
    """Revierte la migración: copia los precios de vuelta a Producto"""
    Prenda = apps.get_model('inventario', 'Prenda')
    Producto = apps.get_model('inventario', 'Producto')
    
    # Para cada producto, tomar el precio de su primera prenda (si existe)
    for producto in Producto.objects.all():
        primera_prenda = producto.prenda_set.first()
        if primera_prenda:
            producto.precio_compra = primera_prenda.precio_compra
            producto.precio_venta = primera_prenda.precio_venta
            producto.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_movimientoinventario_usuario'),
    ]

    operations = [
        # Paso 1: Agregar los campos a Prenda (con null=True para permitir migración)
        migrations.AddField(
            model_name='prenda',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prenda',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        # Paso 2: Migrar los datos
        migrations.RunPython(migrate_precios_to_prenda, reverse_migrate_precios_to_producto),
        # Paso 3: Eliminar los campos de Producto
        migrations.RemoveField(
            model_name='producto',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_venta',
        ),
    ]
